package eu.bittrade.libs.steem.api.wrapper.util;

/**
 * This is the representation of <a href=
 * "https://github.com/steemit/steem/blob/master/libraries/protocol/include/steemit/protocol/operations.hpp">the
 * official transaction type of steem</a>.
 * 
 * Like for the official type, it is important the order of this items does not
 * get changed! Otherwise the transactions will use a wrong type.
 * 
 * @author<a href="http://steemit.com/@dez1337">dez1337</a>
 */
public enum OperationTypes {
    VOTE_OPERATION, COMMENT_OPERATION,

    TRANSFER_OPERATION, TRANSFER_TO_VESTING_OPERATION, WITHDRAW_VESTING_OPERATION,

    LIMIT_ORDER_CREATE_OPERATION, LIMIT_ORDER_CANCEL_OPERATION,

    FEED_PUBLISH_OPERATION, CONVERT_OPERATION,

    ACCOUNT_CREATE_OPERATION, ACCOUNT_UPDATE_OPERATION,

    WITNESS_UPDATE_OPERATION, ACCOUNT_WITNESS_VOTE_OPERATION, ACCOUNT_WITNESS_PROXY_OPERATION,

    POW_OPERATION,

    CUSTOM_OPERATION,

    REPORT_OVER_PRODUCTION_OPERATION,

    DELETE_COMMENT_OPERATION, CUSTOM_JSON_OPERATION, COMMENT_OPTIONS_OPERATION, SET_WITHDRAW_VESTING_ROUTE_OPERATION, LIMIT_ORDER_CREATE2_OPERATION, CHALLENGE_AUTHORITY_OPERATION, PROVE_AUTHORITY_OPERATION, REQUEST_ACCOUNT_RECOVERY_OPERATION, RECOVER_ACCOUNT_OPERATION, CHANGE_RECOVERY_ACCOUNT_OPERATION, ESCROW_TRANSFER_OPERATION, ESCROW_DISPUTE_OPERATION, ESCROW_RELEASE_OPERATION, POW2_OPERATION, ESCROW_APPROVE_OPERATION, TRANSFER_TO_SAVINGS_OPERATION, TRANSFER_FROM_SAVINGS_OPERATION, CANCEL_TRANSFER_FROM_SAVINGS_OPERATION, CUSTOM_BINARY_OPERATION, DECLINE_VOTING_RIGHTS_OPERATION, RESET_ACCOUNT_OPERATION, SET_RESET_ACCOUNT_OPERATION,

    /// VIRTUAL OPERATIONS BELOW THIS POINT
    FILL_CONVERT_REQUEST_OPERATION, AUTHOR_REWARD_OPERATION, CURATION_REWARD_OPERATION, COMMENT_REWARD_OPERATION, LIQUIDITY_REWARD_OPERATION, INTEREST_OPERATION, FILL_VESTING_WITHDRAW_OPERATION, FILL_ORDER_OPERATION, SHUTDOWN_WITNESS_OPERATION, FILL_TRANSFER_FROM_SAVINGS_OPERATION, HARDFORK_OPERATION, COMMENT_PAYOUT_UPDATE_OPERATION;
}
